# Generated by Django 5.0.4 on 2024-08-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.IntegerField(default='')),
                ('acc_holder', models.CharField(max_length=50)),
                ('acc_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
