# Generated by Django 5.0.4 on 2024-08-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='acc_no',
            field=models.IntegerField(),
        ),
    ]
