# Generated by Django 5.0.4 on 2024-08-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bank_acc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='acc_no',
            field=models.CharField(max_length=50),
        ),
    ]
